(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function m(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ba(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ca(a){return a instanceof Array?a:ba(m(a))}var da=[],ea=[],fa=[],ha=[],ia=setTimeout;function la(){}
function ma(a,b){return function(){a.apply(b,arguments)}}function n(a){if(!(this instanceof n))throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.D=0;this.da=!1;this.G=void 0;this.L=[];na(a,this)}function oa(a,b){for(;3===a.D;)a=a.G;0===a.D?a.L.push(b):(a.da=!0,n.ea(function(){var c=1===a.D?b.Ea:b.Fa;if(null===c)(1===a.D?pa:qa)(b.promise,a.G);else{try{var d=c(a.G)}catch(e){qa(b.promise,e);return}pa(b.promise,d)}}))}
function pa(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var c=b.then;if(b instanceof n){a.D=3;a.G=b;ra(a);return}if("function"===typeof c){na(ma(c,b),a);return}}a.D=1;a.G=b;ra(a)}catch(d){qa(a,d)}}function qa(a,b){a.D=2;a.G=b;ra(a)}function ra(a){2===a.D&&0===a.L.length&&n.ea(function(){a.da||n.xa(a.G)});for(var b=0,c=a.L.length;b<c;b++)oa(a,a.L[b]);a.L=null}
function sa(a,b,c){this.Ea="function"===typeof a?a:null;this.Fa="function"===typeof b?b:null;this.promise=c}function na(a,b){var c=!1;try{a(function(d){c||(c=!0,pa(b,d))},function(d){c||(c=!0,qa(b,d))})}catch(d){c||(c=!0,qa(b,d))}}n.prototype["catch"]=function(a){return this.then(null,a)};n.prototype.then=function(a,b){var c=new this.constructor(la);oa(this,new sa(a,b,c));return c};
n.prototype["finally"]=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})};
n.all=function(a){return new n(function(b,c){function d(h,k){try{if(k&&("object"===typeof k||"function"===typeof k)){var l=k.then;if("function"===typeof l){l.call(k,function(q){d(h,q)},c);return}}e[h]=k;0===--f&&b(e)}catch(q){c(q)}}if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.all accepts an array"));var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,g=0;g<e.length;g++)d(g,e[g])})};
n.resolve=function(a){return a&&"object"===typeof a&&a.constructor===n?a:new n(function(b){b(a)})};n.reject=function(a){return new n(function(b,c){c(a)})};n.race=function(a){return new n(function(b,c){if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.race accepts an array"));for(var d=0,e=a.length;d<e;d++)n.resolve(a[d]).then(b,c)})};n.ea="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){ia(a,0)};
n.xa=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};function p(){}var r=[];function ta(a,b){if(!b||"function"!==typeof b)return!1;try{var c=""+b}catch(h){return!1}var d=c.length;if(d>35+a.length)return!1;for(var e=d-13,f=0,g=8;g<d;g+=1){f="[native code]"[f]===c[g]||7===f&&"-"===c[g]?f+1:0;if(12===f)return!0;if(!f&&g>e)break}return!1}function ua(a,b){var c=ta(a,b);b&&!c&&r.push([a,b]);return c}function t(a,b){return ua(b,a)&&a}
var va=t(String.prototype.indexOf,"indexOf");function wa(a,b){for(var c=0,d=a.length-b.length,e=0;e<a.length;e+=1){c=a[e]===b[c]?c+1:0;if(c===b.length)return e-b.length+1;if(!c&&e>d)break}return-1}var xa=va?function(a,b){return va.call(a,b)}:wa;function ya(a,b){return!(!a||-1===xa(a,b))}function za(a,b){return b(a)}function u(a){return function(b){return function(c){return a(b,c)}}}function v(a){return function(b){return function(c){return a(c,b)}}}
var Aa=u(function(a,b){return a===b}),w=u(za),Ba=Aa(null);function x(a){return"function"===typeof a}var y=Aa(void 0);function z(a){return y(a)||Ba(a)}var Ca=t(Array.from,"from");function Da(a){for(var b=a.length,c=[],d=0;d<b;d+=1)c.push(a[d]);return c}function A(a){if(Ca)try{return Ca(a)}catch(b){}return Da(a)}
function Fa(a,b,c){b=void 0===b?[]:b;c=c||{};var d=b.length,e=a;x(e)&&(e="d",c[e]=a);var f;d?1===d?f=c[e](b[0]):2===d?f=c[e](b[0],b[1]):3===d?f=c[e](b[0],b[1],b[2]):4===d&&(f=c[e](b[0],b[1],b[2],b[3])):f=c[e]();return f}var Ga=t(Function.prototype.bind,"bind");
function Ha(){var a=A(arguments);a=m(a);var b=a.next().value,c=a.next().value,d=ba(a);return function(){var e=[].concat(ca(d),ca(A(arguments)));if(Function.prototype.call)return Function.prototype.call.apply(b,[c].concat(ca(e)));if(c){for(var f="_b";c[f];)f+="_"+f.length;c[f]=b;e=c[f]&&Fa(f,e,c);delete c[f];return e}return Fa(b,e)}}var B=Ga?function(){var a=A(arguments),b=m(a);a=b.next().value;var c=b.next().value;b=ba(b);return Ga.apply(a,[c].concat(b))}:Ha;
function C(a,b){return B.apply(null,[b,null].concat(ca(a)))}function D(a,b){return B(b,null,a)}function E(a,b){return B(b[a],b)}var Ia=u(C),Ja=u(E),Ka=t(Array.prototype.reduce,"reduce");function La(a,b,c){for(var d=0,e=c.length;d<e;)b=a(b,c[d],d),d+=1;return b}var F=Ka?function(a,b,c){return Ka.call(c,a,b)}:La,Ma=v(parseInt)(10),Na=Object.prototype.hasOwnProperty;function Oa(a,b){return z(a)?!1:Na.call(a,b)}
function G(a,b){return a?F(function(c,d){if(z(c))return c;try{return c[d]}catch(e){}return null},a,b.split(".")):null}var H=v(G);function Pa(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return c;return-1}var Qa;function Ra(a){if(Qa)return Qa;var b=!1;try{b=[].indexOf&&0===[void 0].indexOf(void 0)}catch(d){}var c=a.Array&&a.Array.prototype&&t(a.Array.prototype.indexOf,"indexOf");return Qa=a=b&&c?function(d,e){return c.call(e,d)}:Pa}var Sa=Ra(window);function I(a){return a}
function Ta(a,b){return b}function Ua(a){return!a}function J(a,b){var c=[],d=[];var e=b?b:I;return function(){var f=A(arguments),g=e.apply(null,ca(f)),h=Sa(g,d);if(-1!==h)return c[h];f=a.apply(null,ca(f));c.push(f);d.push(g);return f}}
var Va=J(function(a){var b=G(a,"navigator")||{};a=G(b,"userAgent")||"";b=G(b,"vendor")||"";return{za:-1<xa(b,"Apple"),Ja:a}}),Wa=J(H("navigator.userAgent")),Xa=/Firefox\/([0-9]+)/i,Ya=J(function(a){var b=G(a,"document.documentElement.style"),c=G(a,"InstallTrigger");a=-1!==(G(a,"navigator.userAgent")||"").toLowerCase().search(Xa);Xa.lastIndex=0;return!(!(b&&"MozAppearance"in b)||z(c))||a});function Za(a){return"[object Array]"===Object.prototype.toString.call(a)}
var $a=t(Array.isArray,"isArray"),ab=$a?function(a){return $a(a)}:Za;function bb(a,b){var c=G(b,a),d=G(b,"constructor.prototype."+a)||c;try{if(d&&d.apply)return function(){return d.apply(b,arguments)}}catch(e){return c}return d}function cb(){var a=Array.prototype.map;if(!Ya(window))return!0;try{a.call({0:!0,length:-Math.pow(2,32)+1},function(){throw 1;})}catch(b){return!1}return!0}var db=t(Array.prototype.map,"map");function eb(a,b){return F(function(c,d,e){c.push(a(d,e));return c},[],b)}
var K=db&&cb()?function(a,b){return b&&0<b.length?db.call(b,a):[]}:eb,fb=v(K);function M(){var a=A(arguments),b=a.shift();return function(){var c=b.apply(null,arguments);return F(za,c,a)}}var gb=t(Object.keys,"keys");function hb(a){var b=[],c;for(c in a)Oa(a,c)&&b.push(c);return b}var ib=t(Object.entries,"entries");function jb(a){return y(a)?[]:La(function(b,c){b.push([c,a[c]]);return b},[],hb(a))}var kb=ib?function(a){return a?ib(a):[]}:jb,lb=gb?function(a){return gb(a)}:hb;
function mb(){var a=A(arguments),b=m(a);a=b.next().value;for(b=ba(b);b.length;){var c=b.shift(),d;for(d in c)Oa(c,d)&&(a[d]=c[d]);Oa(c,"toString")&&(a.toString=c.toString)}return a}var N=Object.assign||mb,nb=u(function(a,b){return N({},a,b)}),O=window.Promise,ob=t(O,"Promise"),pb=t(G(O,"resolve"),"resolve"),qb=t(G(O,"reject"),"reject"),rb=t(G(O,"all"),"all");if(ob&&pb&&qb&&rb){var sb=function(a){return new Promise(a)};sb.resolve=B(pb,O);sb.reject=B(qb,O);sb.all=B(rb,O);O=sb}else O=n;
function tb(a,b,c){return c?a:b}var ub=C([1,null],tb),vb=C([1,0],tb),wb=Boolean,xb=t(Array.prototype.filter,"filter");function yb(a,b){return La(function(c,d,e){a(d,e)&&c.push(d);return c},[],b)}var zb=xb?function(a,b){return xb.call(b,a)}:yb,Ab=D(wb,zb),Bb=t(Array.prototype.includes,"includes");function Cb(a,b){return 1<=yb(Aa(a),b).length}var Db=Bb?function(a,b,c){return Bb.call(b,a,c)}:Cb;
function Eb(a){return F(function(b,c){var d=m(c),e=d.next().value,f=d.next().value;d=f.Ca;f=a[f.Ga];b[e]=d?d(f):f;return b},{},kb(Fb))}var P=J(function(a){return a.id+":"+a.ga}),Q=J(function(a){a=a.Ya=a.Ya||{};var b=a._metrika=a._metrika||{};return{Ua:function(c,d){Oa(b,c)||(b[c]=d);return this},m:function(c,d){b[c]=d;return this},g:function(c,d){var e=b[c];return Oa(b,c)||y(d)?e:d}}});function Gb(a,b){var c=Q(a).g("counters",{}),d=P(b);return c[d]}var Hb=t(Array.prototype.some,"some");
function Ib(a,b){for(var c=0;c<b.length;c+=1)if(c in b&&a.call(b,b[c],c))return!0;return!1}var Jb=Hb?function(a,b){return Hb.call(b,a)}:Ib;function Kb(a,b){return function(){var c=Q(arguments[0]),d=c.g("m1570",{}),e=G(d,a);e||(e=J(b),d[a]=e,c.m("m1570",d));return e.apply(null,arguments)}}function Lb(a,b){for(var c="",d=0;d<b.length;d+=1)c+=""+(d?a:"")+b[d];return c}var Mb=t(Array.prototype.join,"join"),R=Mb?function(a,b){return Mb.call(b,a)}:Lb,Nb="hash host hostname href pathname port protocol search".split(" ");
function S(a){return F(function(b,c){var d=G(a,"location."+c);b[c]=d?""+d:"";return b},{},Nb)}var Ob=/(?:^|\.)(?:(ya\.ru)|(?:yandex)\.(\w+|com?\.\w+))$/,Pb=J(function(a){a=S(a).hostname;var b=!1;a&&(b=-1!==a.search(Ob));return b});function Qb(a){return a?ab(a)?a:Ca?Ca(a):"number"===typeof a.length&&0<=a.length?Da(a):[]:[]}
var Rb=J(Ra),Sb=J(M(H("String.fromCharCode"),D("fromCharCode",ua),Ua)),Tb=J(M(Wa,E("test",/ipad|iphone|ipod/i))),Ub=J(function(a){a=Va(a);var b=a.Ja;return a.za&&!b.match("CriOS")}),Vb=J(function(a){a=(Wa(a)||"").toLowerCase();return ya(a,"android")&&ya(a,"mobile")}),Wb="other none unknown wifi ethernet bluetooth cellular wimax mixed".split(" "),Xb=J(function(a){var b=G(a,"navigator.connection.type");if(y(b))return null;a=Rb(a)(b,Wb);return-1===a?b:""+a}),Yb=J(M(H("document.addEventListener"),Ua)),
Zb=J(function(a){var b=G(a,"navigator")||{};return F(function(c,d){return c||G(b,d)},"",["language","userLanguage","browserLanguage","systemLanguage"])}),$b=J(function(a){return(G(a,"top")||a)!==a}),ac=J(H("top.contentWindow")),bc=J(function(a){var b=!1;try{b=a.navigator.javaEnabled()}catch(c){}return b});function cc(a){return Db("prerender",K(D(G(a,"document"),G),["webkitVisibilityState","visibilityState"]))}
var dc=J(function(a){var b=Wa(a)||"",c=b.match(/Mac OS X ([0-9]+)_([0-9]+)/);c=c?[+c[1],+c[2]]:[0,0];b=b.match(/iPhone OS ([1-9]+)_([0-9]+)/);return 14<=(b?+b[1]:0)?!0:(Tb(a)||10<c[0]||10===c[0]&&13<=c[1])&&Ub(a)}),ec=/Edg\/(\d+)\./,fc=J(function(a){var b;if(!(b=dc(a)))a:{if(Ya(a)&&(b=Wa(a).match(Xa))&&b.length){b=68<=+b[1];break a}b=!1}if(!b)a:{if((a=Wa(a))&&(a=a.match(ec))&&1<a.length){b=79<=Ma(a[1]);break a}b=!1}return b});
function gc(a){return Tb(a)||Vb(a)||/mobile/i.test(Wa(a))||!y(G(a,"orientation"))}var hc=/^\s+|\s+$/g,ic=t(String.prototype.trim,"trim");function jc(a){return a?ic?ic.call(a):(""+a).replace(hc,""):""}var kc=u(function(a,b){return b.replace(a,"")}),lc=kc(/\s/g),mc=kc(/\D/g),nc=["metrika_enabled"],oc=[];function pc(a,b){var c=qc;return!oc.length||Db(b,nc)?!0:F(function(d,e){return d&&e(a,c,b)},!0,oc)}
function rc(a){try{var b=a.document.cookie;if(!z(b)){var c={};K(function(d){d=m(d.split("="));var e=d.next().value;d=d.next().value;e=jc(e);var f="";try{f=decodeURIComponent(d)}catch(g){}c[e]=jc(f)},(b||"").split(";"));return c}}catch(d){}return null}var sc=Kb("gsc",rc);function qc(a,b){var c=sc(a);return c?c[b]||null:null}var tc=/:\d+$/;
function uc(a,b,c,d,e,f,g){g=void 0===g?!1:g;if(pc(a,b)){var h=b+"="+encodeURIComponent(c)+";";if(d){var k=new Date;k.setTime(k.getTime()+6E4*d);h+="expires="+k.toUTCString()+";"}e&&(d=e.replace(tc,""),h+="domain="+d+";");try{a.document.cookie=h+("path="+(f||"/")),g||(sc(a)[b]=c)}catch(l){}}}
var vc=J(function(a){var b=(S(a).host||"").split(".");return 1===b.length?b[0]:F(function(c,d,e){e+=1;2<=e&&!c&&(e=R(".",b.slice(-e)),uc(a,"metrika_enabled","1",0,e,void 0,!0),(d=(d=rc(a))&&d.metrika_enabled)&&uc(a,"metrika_enabled","",-100,e,void 0,!0),d&&(c=e));return c},"",b)});
function wc(a,b,c){b=void 0===b?"_ym_":b;c=void 0===c?"":c;var d=vc(a),e=1===(d||"").split(".").length?d:"."+d,f=c?"_"+c:"";return{ha:function(g,h,k){uc(a,""+b+g+f,"",-100,h||e,k,!1);return this},g:function(g){return qc(a,""+b+g+f)},m:function(g,h,k,l,q){uc(a,""+b+g+f,h,k,l||e,q);return this}}}
var xc=J(wc),yc=J(function(a){var b=xc(a),c="1"===b.g("debug"),d=S(a).href;(d=-1<xa(d,"_ym_debug=1"))||(d=S(a).href,d=-1<xa(d,"_ym_debug=2"));var e=a._ym_debug;!e&&!d||c||(a=S(a),b.m("debug","1",void 0,a.host));return!!(c||e||d)});function zc(){return{}}var Ac=Yb(window),Bc=Ac?512:2048,Cc=Ac?100:400,Dc=["http.0.st..rt.","network error occurred","send beacon","Content Security Policy","DOM Exception 18"];function Ec(a){throw a;}var Fc;function Gc(a){this.message=a}
var Hc=function(a){return function(b,c){c=void 0===c?!1:c;if(Fc)var d=new Fc(b);else ua("Error",a.Error)?(Fc=a.Error,d=new a.Error(b)):(Fc=Gc,d=new Fc(b));c&&(d.unk=!0);return d}}(window),Ic=E("test",RegExp("^http."));function Jc(a){var b="";ab(a)?b=R(".",a):"string"===typeof a&&(b=a);return Hc("err.kn(1570)"+b)}var Kc=E("test",RegExp("^err.kn"));function T(a,b){return b?a(b):a()}var Lc=[];
function Mc(a){a=G(a,"performance")||G(a,"webkitPerformance");var b=G(a,"timing.navigationStart"),c=G(a,"now");c&&(c=B(c,a));return[b,c]}function Nc(a,b){var c=m(b||Mc(a)),d=c.next().value;c=c.next().value;return!isNaN(d)&&x(c)?Math.round(c()+d):a.Date.now?a.Date.now():(new a.Date).getTime()}
function U(a,b,c,d){var e=c||Ec;return function(){var f=d;try{f=e.apply(null,arguments)}catch(l){var g=l,h="u.a.e",k="";g&&("object"===typeof g?(g.unk&&Ec(g),h=g.message,k="string"===typeof g.stack&&g.stack.replace(/\n/g,"\\n")||"n.s.e.s"):h=""+g);Kc(h)||Jb(D(h,ya),Dc)||Ic(h)&&.1<=a.Math.random()||K(M(I,Ia(["jserrs",h,b,k]),T),Lc)}return f}}function V(a,b,c){return function(){return U(arguments[0],a,b,c).apply(this,arguments)}}var Oc=J(V("dc.init",function(){return{log:p,warn:p,error:p}}),Ta);
function Pc(a,b,c,d){Oc(a,b).log(c,d)}var Qc=J(function(a){a=!(!a.addEventListener||!a.removeEventListener);return{Ha:a,l:a?"addEventListener":"attachEvent",T:a?"removeEventListener":"detachEvent"}});function Rc(a,b,c,d,e,f){a=Qc(a);var g=a.l,h=a.T;f=f?h:g;if(b[f])if(a.Ha)if(e)b[f](c,d,e);else b[f](c,d);else b[f]("on"+c,d)}
var Sc=J(function(a){var b=!1;if(!a.addEventListener)return b;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0;return 1}});a.addEventListener("test",p,c)}catch(d){}return b}),Tc=u(function(a,b){if(null!==b)return a?N({capture:!0,passive:!0},b||{}):!!b}),Uc=J(function(a){var b=Sc(a),c=Tc(b),d={};return N(d,{l:function(e,f,g,h){K(function(k){var l=c(h);Rc(a,e,k,g,l,!1)},f);return B(d.ta,d,e,f,g,h)},ta:function(e,f,g,h){K(function(k){var l=c(h);Rc(a,e,k,g,l,!0)},f)}})}),Vc=["webkitvisibilitychange",
"visibilitychange"];function Wc(a,b){K(M(I,E("push",a)),b);return a}R("",["\\.("+R("|","3gp 7z aac ac3 acs ai avi ape apk asf bmp bz2 cab cdr crc32 css csv cue divx dmg djvu? doc(x|m|b)? emf eps exe flac? flv iso swf gif t?gz jpe?g? js m3u8? m4a mp(3|4|e?g?) m4v md5 mkv mov msi ods og(g|m|v) psd rar rss rtf sea sfv sit sha1 svg tar tif?f torrent ts txt vob wave? wma wmv wmf webm ppt(x|m|b)? xls(x|m|b)? pdf phps png xpi g?zip".split(" "))+")$"]);var Xc={};
function Yc(a,b){if(!b)return null;try{return a.JSON.parse(b)}catch(c){return null}}function Zc(a,b){try{return a.JSON.stringify(b,null,void 0)}catch(c){return null}}function $c(a){try{return a.localStorage}catch(b){}return null}function ad(a,b){var c=$c(a);try{c.removeItem(b)}catch(d){}}function bd(a,b){var c=$c(a);try{return Yc(a,c.getItem(b))}catch(d){}return null}function cd(a,b,c){var d=$c(a);a=Zc(a,c);if(!Ba(a))try{d.setItem(b,a)}catch(e){}}
var dd=J(function(a){cd(a,"_ymBRC","1");var b="1"!==bd(a,"_ymBRC");b||ad(a,"_ymBRC");return b});function ed(a,b,c){var d=""+(void 0===c?"_ym":c)+(void 0===b?"":b);d&&(d+="_");return{Pa:dd(a),g:function(e,f){var g=bd(a,""+d+e);return Ba(g)&&!y(f)?f:g},m:function(e,f){cd(a,""+d+e,f);return this},ha:function(e){ad(a,""+d+e);return this}}}var fd=J(ed),gd=J(ed,function(a,b,c){return""+b+c});function hd(a){if(z(a))return!1;a=a.nodeType;return 3===a||8===a}
var id=J(function(a){a=G(a,"document")||{};return(""+(a.characterSet||a.charset||"")).toLowerCase()}),jd=J(M(H("document"),D("createElement",bb)));function kd(a,b,c){var d=y(c);y(b)&&d?(d=1,b=1073741824):d?d=1:(d=b,b=c);return a.Math.floor(a.Math.random()*(b-d))+d}function ld(a){return(10>a?"0":"")+a}function W(a){var b=a.ca;return 0!==b?b:Nc(a.N,a.F)}function md(a){return Math.round(W(a)/1E3)}
var X=J(function(a){var b=Uc(a),c=Mc(a),d={N:a,ca:0,F:c,Oa:Nc(a,c)},e=m(c);c=e.next().value;e=e.next().value;c&&e||b.l(a,["beforeunload","unload"],function(){0===d.ca&&(d.ca=Nc(a,d.F))});return w(d)}),nd=/\/$/;function od(a){var b=Q(a),c=b.g("hitId");c||(c=kd(a),b.m("hitId",c));return c}function pd(a,b){var c=fd(a),d=xc(a),e=b.Y||"uid";return[c.g(e),d.g(e)]}var qd=Kb("r",function(a,b){var c=m(pd(a,b)),d=c.next().value;return!c.next().value&&d});
function rd(a,b){var c=b.Y,d=c||"uid";c=c?a.location.hostname:void 0;var e=xc(a),f=fd(a),g=X(a)(md),h=m(pd(a,b)),k=h.next().value;h=h.next().value;var l=e.g("d");qd(a,b);var q=!1;!h&&k&&(h=k,q=!0);if(!h)h=R("",[g,kd(a,1E6,999999999)]),q=!0;else if(!l||15768E3<g-Ma(l))q=!0;q&&!b.$&&(e.m(d,h,525600,c),e.m("d",""+g,525600,c));f.m(d,h);return h}function Y(a,b,c,d){b=U(a,"d.err."+(d||"def"),b);return bb("setTimeout",a)(b,c)}function sd(a,b){return function(c){return c(a,b)}}
function td(a){function b(e){G(c,d)?e():Y(a,D(e,b),100)}var c=void 0===c?a:c;var d=(c.nodeType?"contentWindow.":"")+"document.body";return w(function(e,f){b(f)})}function ud(a){var b=[],c={Qa:b};c.l=M(E("push",b),D(c,I));c.T=M(v(Ra(a))(b),v(E("splice",b))(1),D(c,I));c.B=M(I,v(T),fb(b));return c}
function vd(a){var b={};return{l:function(c,d){K(function(e){G(b,e)||(b[e]=ud(a));b[e].l(d)},c);return this},T:function(c,d){K(function(e){G(b,e)&&b[e].T(d)},c);return this},B:function(c,d){return G(b,c)?U(a,"e."+c,b[c].B,[])(d):[]}}}var wd=J(function(){return{H:{},pending:{},children:{}}}),xd=H("postMessage");
function yd(a,b){return function(c,d){var e={W:X(a)(W),key:a.Math.random(),dir:0};c.length&&(e.W=Ma(c[0]),e.key=parseFloat(c[1]),e.dir=Ma(c[2]));N(d,b);var f={};f=(f.data=d,f.__yminfo=R(":",["__yminfo",e.W,e.key,e.dir]),f);return{meta:e,ra:Zc(a,f)||""}}}var zd=V("s.f",function(a,b,c,d,e){b=b(d);var f=wd(a),g=R(":",[b.meta.W,b.meta.key]);if(xd(c)){f.pending[g]=e;try{c.postMessage(b.ra,"*")}catch(h){delete f.pending[g];return}Y(a,function(){delete f.pending[g]},5E3,"if.s")}});
function Ad(a){if(ua("MutationObserver",a.MutationObserver)){var b=wd(a).children,c=new a.MutationObserver(function(){K(function(d){G(b[d],"window.window")||delete b[d]},lb(b))});td(a)(sd(p,function(){c.observe(a.document.body,{subtree:!0,childList:!0})}))}}
function Bd(a,b){var c=wd(a);b.l(["initToParent"],function(d){var e=m(d);d=e.next().value;e=e.next().value;window.window&&(c.children[e.counterId]={info:e,window:d.source})}).l(["initToChild"],function(d){var e=m(d);d=e.next().value;e=e.next().value;d.source===a.parent&&b.B("parentConnect",[d,e])}).l(["parentConnect"],function(d){var e=m(d);d=e.next().value;e=e.next().value;e.counterId&&(c.H[e.counterId]={info:e,window:d.source})})}
var Cd=V("s.fh",function(a,b,c,d,e,f){var g=null,h=null,k=wd(a),l=null;try{g=Yc(a,f.data),h=g.__yminfo,l=g.data}catch(q){return}if(!z(h)&&h.substring&&"__yminfo"===h.substring(0,8)&&!z(l)&&(a=h.split(":"),4===a.length))if(g=b.id,h=m(a),h.next(),b=h.next().value,a=h.next().value,h=h.next().value,!ab(l)&&l.type&&"0"===h&&l.counterId){if(!l.toCounter||l.toCounter==g){k=null;try{k=f.source}catch(q){}!Ba(k)&&xd(k)&&(f=d.B(l.type,[f,l]),e=K(M(I,nb(e)),f.concat([void 0])),l=c([b,a,l.counterId],e),k.postMessage(l.ra,
"*"))}}else h===""+g&&ab(l)&&zb(function(q){return!(!q.hid||!q.counterId)},l).length===l.length&&(c=k.pending[R(":",[b,a])])&&c.apply(null,[f].concat(l))}),Dd=J(function(a,b){var c=bb("getElementsByTagName",G(a,"document")),d=wd(a),e=xd(a),f=vd(a),g=Uc(a);if(!c||!e)return null;c=c.call(a.document,"iframe");e={};e=(e.counterId=b.id,e.hid=""+od(a),e);fc(a)&&(e.duid=rd(a,b));Bd(a,f);Ad(a);var h=yd(a,e),k=C([a,D([],h)],zd);K(function(l){var q=null;try{q=l.contentWindow}catch(L){}q&&k(q,{type:"initToChild"},
function(L,ja){f.B("initToParent",[L,ja])})},c);$b(a)&&k(a.parent,{type:"initToParent"},function(l,q){f.B("parentConnect",[l,q])});g.l(a,["message"],C([a,b,h,f,e],Cd));return{ya:f,H:d.H,children:d.children,Sa:k}},M(Ta,P)),Ed=J(function(a,b){if(!fc(a)||!$b(a))return rd(a,b);var c=Dd(a,b);return c&&c.H[b.id]?c.H[b.id].info.duid||rd(a,b):rd(a,b)},function(a,b){return""+b.Y+b.$}),Fd=J(M(X,w(function(a){return-(new a.N.Date).getTimezoneOffset()}))),Gd=M(X,w(function(a){a=new a.N.Date;return R("",K(ld,
[a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds()]))})),Hd=M(X,w(md)),Id=J(function(a){a=Q(a);var b=a.g("counterNum",0)+1;a.m("counterNum",b);return b},M(Ta,P)),Z={},Jd=(Z.vf=D("1mhcdgigppdtv9u328",I),Z.nt=Xb,Z.fu=function(a,b,c){var d=c.V;if(!d)return null;b=(G(a,"document.referrer")||"").replace(nd,"");c=(d["page-ref"]||"").replace(nd,"");d=d["page-url"];a=S(a).href!==d;b=b!==c;c=0;a&&b?c=3:b?c=1:a&&(c=2);return c},Z.en=id,Z.la=Zb,Z.ut=function(a,b,c){var d=
c.Z;c=c.V;d=d&&d.Ra;c&&(Pb(a)||b.va||d)&&(c.ut="noindex");return null},Z.v=D("1570",I),Z.cn=Id,Z.dp=function(a){var b=Q(a),c=b.g("bt",{});if(y(b.g("bt"))){var d=G(a,"navigator.getBattery");try{c.p=d&&d.call(a.navigator)}catch(e){}b.m("bt",c);c.p&&c.p.then&&c.p.then(U(a,"bi:dp.p",function(e){c.Ka=G(e,"charging")&&0===G(e,"chargingTime")}))}return vb(c.Ka)},Z.ls=J(function(a,b){var c=gd(a,b.id),d=X(a),e=c.g("lsid");return+e?e:(d=kd(a,0,d(W)),c.m("lsid",d),d)},Ta),Z.hid=od,Z.phid=function(a,b){if(!$b(a))return null;
var c=Dd(a,b);if(!c)return null;var d=lb(c.H);return d.length?c.H[d[0]].info.hid:null},Z.z=Fd,Z.i=Gd,Z.et=Hd,Z.c=M(H("navigator.cookieEnabled"),ub),Z.rn=M(I,kd),Z.rqn=function(a,b,c){c=c.V;if(!c||c.nohit)return null;b=P(b);a=gd(a,b);b=(a.g("reqNum",0)||0)+1;a.m("reqNum",b);if(a.g("reqNum")===b)return b;a.ha("reqNum");return null},Z.u=Ed,Z.w=function(a){var b=G(a,"visualViewport.width");var c=G(a,"visualViewport.height"),d=G(a,"visualViewport.scale");if(b=z(b)||z(c)?null:[Math.floor(b),Math.floor(c),
d]){c=m(b);var e=c.next().value;b=c.next().value;c=c.next().value;a=[a.Math.round(e*c),a.Math.round(b*c)]}else{c=G(a,"document")||{};b=c.documentElement;if("CSS1Compat"===c.compatMode)e=b;else{c=G(a,"document");try{e=c.getElementsByTagName("body")[0]}catch(f){e=null}e=e||b}a=[G(e,"clientWidth")||a.innerWidth,G(e,"clientHeight")||a.innerHeight]}e=m(a);a=e.next().value;e=e.next().value;return a+"x"+e},Z.s=function(a){var b=G(a,"screen");if(b){a=G(b,"width");var c=G(b,"height");b=G(b,"colorDepth")||
G(b,"pixelDepth");return R("x",[a,c,b])}return null},Z.sk=H("devicePixelRatio"),Z.ifr=M($b,ub),Z.j=M(bc,ub),Z.sti=function(a){return $b(a)&&ac(a)?"1":null},Z),Kd=J(function(){return Wc(lb(Jd),lb(Xc))}),Ld=J(zc,P);function Md(a,b,c){if(fc(a)&&$b(a)){var d=Ld(b);if(!d.Aa){d.Aa=!0;b=Dd(a,b);if(!b){c();return}d.C=[];var e=function(){d.C&&(K(T,d.C),d.C=null)};Y(a,e,3E3);b.ya.l(["initToChild"],e)}d.C?d.C.push(c):c()}else c()}var Nd=J(function(){return{ia:null,C:[]}},P);
function Od(a,b,c){var d=a.J;d?(a=a.J)&&a.g("pv")&&!a.g("ar")?(b.ia=d,c()):b.C?b.C.push(c):c():c()}var Pd=/^[a-z][\w.+-]+:/i;
function Qd(a,b){var c=S(a),d=c.href,e=c.host,f=-1;if("string"!==typeof b||y(b))return d;c=b.replace(hc,"");if(-1!==c.search(Pd))return c;var g=c.charAt(0);if("?"===g&&(f=d.search(/\?/),-1===f)||"#"===g&&(f=d.search(/#/),-1===f))return d+c;if(-1!==f)return d.substr(0,f)+c;if("/"===g){if(f=xa(d,e),-1!==f)return d.substr(0,f+e.length)+c}else return d=d.split("/"),d[d.length-1]=c,R("/",d);return""}
D([[function(a){return{R:function(b,c){var d=a.document,e=b.J;if(e&&cc(a)){var f=Uc(a),g=function(h){cc(a)||(f.ta(d,Vc,g),c());return h};f.l(d,Vc,g);e.m("pr","1")}else c()}}},1],[function(a,b){return{R:function(c,d){var e=Nd(b);e=C([c,e,d],Od);Md(a,b,e)},La:function(c,d){var e=c.J,f=Nd(b);if(e){var g=f.C;f.ia===e&&g&&(K(T,g),f.C=null)}d()}}},2],[function(a){return function(b,c){return{R:function(d,e){var f=d.J,g=d.V;f&&g&&K(function(h){var k=Jd[h];k&&(k=V("bi:"+h,k,null)(b,c,d),f.Ta(h,k))},a||Kd());
e()}}}}(),3],[function(a){return{R:function(b,c){var d=b.J;if(d){var e=a.document.title;b.Z&&b.Z.title&&(e=b.Z.title);var f=bb("getElementsByTagName",a.document);"string"!==typeof e&&f&&(e=f("title"),e=(e=G(e,"0.innerHtml"))?e:"");e=e.slice(0,Cc);d.m("t",e)}c()}}},4]],function(a,b,c){for(var d=[b,c],e=-1E4,f=0;f<a.length;f+=1){var g=m(a[f]),h=g.next().value;g=g.next().value;if(c===g&&h===b)return;if(c<g&&c>=e){a.splice(f,0,d);return}e=g}a.push(d)})(function(a){return{R:function(b,c){var d=b.V;if(!b.J||
!d)return c();var e=d["page-ref"],f=d["page-url"];e&&f!==e?d["page-ref"]=Qd(a,e):delete d["page-ref"];d["page-url"]=Qd(a,f).slice(0,Bc);return c()}}},-100);function Rd(a){return a.ba||a.ka.length<=a.S}function Sd(a){a.ba=!0}function Td(a){a.ba=!1}function Ud(a){Rd(a)&&Ec(Hc("i"));var b=a.Ba(a.ka[a.S]);a.S+=1;return b}var Vd=u(function(a,b){for(var c=[];!Rd(b);){var d=Ud(b);a(d,function(e){return e(b)});c.push(d)}return c});
function Wd(a,b){return function(c){var d=X(a),e=d(W);return Vd(function(f,g){d(W)-e>=b&&g(Sd)})(c)}}var Xd=/^\d+$/,Yd={id:function(a){a=""+(a||"0");Xd.test(a)||(a="0");try{var b=Ma(a)}catch(c){b=0}return b},ga:function(a){return""+(a||0===a?a:"0")},$:wb,va:wb},Fb=F(function(a,b){var c=m(b),d=c.next().value;c=c.next().value;a[d]={Ga:c,Ca:Yd[d]};return a},{},kb({id:"id",va:"ut",ga:"type",Y:"ldc",$:"nck",Na:"url",Ma:"referrer"}));B(O.reject,O,Jc());
function Zd(a,b){b=void 0===b?p:b;var c=void 0===c?!1:c;var d=ud(a);if(r&&x(r.push)){var e=r.push;r.push=function(){var f=A(arguments),g=m(f).next().value;c&&d.B(g);f=e.apply(r,f);c||d.B(g);return f};b({Da:d,unsubscribe:function(){r.push=e}});K(d.B,r)}}function $d(a,b){return function(c){var d=c[a];d?(d.oa=!0,d.na(b)):c[a]={promise:O.resolve(b),oa:!0,na:p}}}var ae=u(function(a,b){if(!b[a]){var c,d=new O(function(e){c=e});b[a]={na:c,promise:d,oa:!1}}return b[a].promise}),be=J(M(zc,w));
function ce(a,b){be()($d(a,b))}function de(a,b){var c=P(a);return be()(ae(c)).then(b)}function ee(a,b){if(a.postMessage&&!a.attachEvent){var c=Uc(a),d="__ym__promise_"+kd(a)+"_"+kd(a),e=p;e=c.l(a,["message"],U(a,"as",function(f){try{var g=f.data}catch(h){return}g===d&&(e(),f.stopPropagation&&f.stopPropagation(),b())}));a.postMessage(d,"*")}else Y(a,b,0,"as")}R(",",K(function(a){return'input[type="'+a+'"]'},["button","submit","reset","file"]));
function fe(a,b,c,d,e){function f(k){return x(d)?d(k)?a.NodeFilter.FILTER_ACCEPT:a.NodeFilter.FILTER_REJECT:a.NodeFilter.FILTER_ACCEPT}e=void 0===e?-1:e;var g=void 0===g?!1:g;var h=f(b);if(x(c)&&(g||h===a.NodeFilter.FILTER_ACCEPT)&&(h&&c(b),!hd(b)))for(b=a.document.createTreeWalker(b,e,d?{acceptNode:f}:null,!1);b.nextNode()&&!1!==c(b.currentNode););}var ge=J(function(a){return R("[^\\d<>]*",a.split(""))}),he=J(function(a){return new RegExp(ge(a),"g")});
function ie(a){return new RegExp("(?:"+R("|",K(ge,lb(a)))+")")}function je(a){var b={7:"8",8:"7"};return 11===a.length&&b[a[0]]?""+b[a[0]]+a.slice(1):a}function ke(a,b){for(var c=[],d=a.split(""),e=b.split(""),f=0,g=0;g<a.length&&!(f>=e.length);g+=1){var h=d[g];"0"<=h&&"9">=h?(c.push(e[f]),f+=1):c.push(d[g])}return R("",c)+b.slice(f+1)}function le(){return C([function(a,b){var c=m(K(mc,b)),d=c.next().value;c=c.next().value;a[d]={I:c,U:b};var e=je(d);e!==d&&(a[e]={I:je(c),U:b});return a},{}],F)}
function me(a,b,c){if(!c)return[];var d=[],e=ie(b),f=["script","style"];fe(a,c,function(g){var h=G(g,"parentNode.nodeName")||"";g===c||Db(h.toLowerCase(),f)||(h=Ab(e.exec(g.textContent||"")||[]),K(function(k){var l=mc(k);y(b[l])||d.push({aa:"text",K:g,P:l,I:ke(k,b[l].I),Ia:g.textContent||""})},h))},function(g){return e.test(g.textContent||"")?1:0},a.NodeFilter.SHOW_TEXT);return d}
function ne(a,b){var c=a.document.body;if(!c)return[];var d=ie(b);return F(function(e,f){var g=G(f,"href");try{var h=decodeURI(g||"")}catch(L){h=""}var k=h;if("tel:"===k.slice(0,4)){var l=m(d.exec(k)||[]).next().value;h=l?mc(l):"";var q=b[h];y(q)||!h&&"*"!==q.U[0]||(e.push({aa:"href",K:f,P:h,I:ke(l,b[h].I),Ia:g}),g=mc(k.slice(4)),g=le()([h?q.U:[g,""]]),Wc(e,me(a,g,f)))}return e},[],Qb(c.querySelectorAll("a")))}
function oe(a,b,c){function d(k){return e(a,b,k)?h[k.P]&&h[k.P].U:null}var e=c.sa,f={},g=void 0===c.ma?(f.href=!0,f.text=!0,f):c.ma,h;return function(k){return new O(function(l,q){k&&k.length||q();h=le()(k);td(a)(sd(D({A:[],F:0},l),function(){var L=X(a),ja=L(W),ka=g.href?ne(a,h):[],Ea=g.text?me(a,h,a.document.body):[];l({A:zb(ab,Ab(K(d,ka.concat(Ea)))),F:L(W)-ja})}))})}}function pe(a,b){Uc(a).l(a,["load"],b.B)}
function qe(a,b){td(a)(sd(p,function(){var c=a.document.body,d={};d=(d.attributes=!0,d.childList=!0,d.subtree=!0,d);ua("MutationObserver",a.MutationObserver)&&(new MutationObserver(b.B)).observe(c,d)}))}function re(a,b){function c(){e=0;f&&(f=!1,e=Y(a,c,1E3),d.B(g))}var d=ud(a),e,f=!1,g;b.l(function(h){f=!0;g=h;e||c();return p});return d}var se=/\S/;
function te(a,b,c,d){function e(){K(function(l){l.style&&N(l.style,{opacity:""})},Qb(c.childNodes));if(b){var k=Gb(a,b);k&&k.extLink("tel:"+d,{})}g();h()}var f=Uc(a),g=p,h=p;g=f.l(c,["mouseenter"],function(k){if(k.target===c){var l=Y(a,e,200,"ph.h.e");h();h=f.l(c,["mouseleave"],function(q){q.target===c&&bb("clearTimeout",a)(l)})}})}
var ue=D(["style","display:inline;margin:0;padding:0;font-size:inherit;color:inherit;line-height:inherit"],function(a,b){b=void 0===b?{}:b;if(!a||1>a.length)return b;F(function(c,d,e){if(e===a.length-1)return c;e===a.length-2?c[d]=a[e+1]:Oa(c,d)||(c[d]={});return c[d]},b,a);return b});
function ve(a,b,c){var d=jd(a),e=c.K,f=c.P,g=e.parentNode,h=e.textContent;if(!("text"===c.aa&&h&&d&&g))return!1;c=d("small");ue(c);var k=lc(h).length;K(E("appendChild",c),F(function(l,q){var L=l.nodes,ja=l.wa,ka=d("small");ka.innerHTML=q;var Ea=se.test(q);ue(ka);Ea&&(ka.style.opacity=""+(k-ja-1)/k);L.push(ka);return{nodes:L,wa:ja+(Ea?1:0)}},{nodes:[],wa:0},h).nodes);te(a,b,c,f);g.insertBefore(c,e);e.textContent="";return!0}
function we(a,b,c){var d={};b=oe(a,b,{sa:ve,ma:(d.href=!0,d)});c=Ab(K(function(f){return"*"===f?f:mc(f)},c));var e=K(M(I,E("concat",[""]),Ja("reverse"),T),c);c=ud(a);d=re(a,c);b=D(e,b);d.l(b);pe(a,c);qe(a,c);b()}
var xe=J(function(a){var b;(b=Sb(a))||(b=!(ua("querySelectorAll",G(a,"Element.prototype.querySelectorAll"))&&a.document.querySelectorAll));return b}),ye=V("phc.h",function(a,b){if(!gc(a)&&!xe(a))return de(b,function(c){if(!G(c,"settings.phchange")){var d=fd(a),e=ya(S(a).search,"_ym_hide_phones=1")||d.g("hide_phones",0);c=G(c,"settings.phhide");e&&!c&&(c=["*"],d.m("hide_phones",1));c&&we(a,b,c)}})["catch"](U(a,"phc.hs"))}),ze=/[\*\.\?\(\)]/g,Ae=J(function(a,b,c){try{var d=c.replace("\\s"," ").replace(ze,
"");b={};Oc(a,"").warn("nnw",(b.name=d,b))}catch(e){}},Ta),Be=V("r.nn",function(a){yc(a)&&Zd(a,function(b){b.Da.l(function(c){var d=m(c);c=d.next().value;d=d.next().value;Ae(a,d,c);r.splice(100)})})}),Ce=[],De=!1,Ee=!1;function Fe(a){if(Ce.length){var b=Ce.shift();Ee?b():Y(a,b,100)}else De=!1}
function Ge(a,b,c){c=void 0===c?1:c;var d=void 0===d?Wd:d;Ee=Infinity===c;return w(function(e,f){function g(){try{var k=b(d(a,c));h=h.concat(k)}catch(l){return e(l)}b(Td);if(b(Rd))return f(h),Fe(a);Ee?(b(d(a,1E4)),f(h),Fe(a)):Y(a,g,100)}var h=[];De?Ce.push(g):(De=!0,g())})}function He(a,b,c,d,e){d=void 0===d?1:d;e=void 0===e?"itc":e;b=w({ka:b,Ba:c||I,ba:!1,S:0});Ge(a,b,d)(sd(U(a,e),p))}D(Jc("ccf"),Ec);
function Ie(a,b,c,d,e){if(b.M&&b.O&&(b.M===a.M&&b.O===a.O||N(a,b,{A:{},X:!0}),0<e&&Wc(a.F,[e]),K(function(f){var g=m(f);f=g.next().value;g=g.next().value;var h={},k={};N(a.A,(k[f]=(h[g]=+(a.A[f]&&a.A[f][g]?a.A[f][g]:0),h),k))},d),K(function(f){var g=m(f);f=g.next().value;g=g.next().value;var h={},k={};N(a.A,(k[f]=(h[g]=1+(a.A[f]?a.A[f][g]:0),h),k))},c),a.ja&&(a.X||c.length))){if(b=Gb(a.N,a.fa))c={},b.params("__ym","phc",(c.clientId=a.M,c.orderId=a.O,c.service_id=a.qa,c.phones=a.A,c.performance=a.F,
c));a.X=!1}}var Je=J(oe);function Ke(a,b,c){a=he(c.P);if("href"===c.aa){var d=c.K;b=d.href;c=b.replace(a,c.I);if(b!==c)return d.href=c,!0}else if((b=null===(d=c.K.textContent)||void 0===d?void 0:d.replace(a,c.I))&&b!==c.K.textContent)return c.K.textContent=b,!0;return!1}var Le=J(Yc,Ta);
function Me(a,b,c){b=wc(a,void 0,b);b=Le(a,b.g("phc_settings")||"");var d=G(b,"clientId"),e=G(b,"orderId"),f=G(b,"service_id"),g=G(b,"phones")||[];return d&&e&&g&&f?Je(a,c.fa,{sa:Ke})(g).then(function(h){return Ie(c,{M:d,O:e,qa:f},h.A,g,h.F)})["catch"](p):O.resolve()}
var Ne=V("phc.p",function(a,b){if(!xe(a))return de(b,function(c){var d=b.id,e=wc(a,void 0,d),f=e.g("phc_settings")||"";if(c=G(c,"settings.phchange")){var g=Zc(a,c)||"";g!==f&&e.m("phc_settings",g)}else f&&(c=Le(a,f));e=G(c,"clientId");f=G(c,"orderId");c=G(c,"phones")||[];e&&f&&c.length&&(f={M:"",O:"",qa:0,A:{},F:[],ja:!1,X:!0,N:a,fa:b},N(f,{ja:!0}),Me(a,d,f),c=ud(a),e=re(a,c),d=B(Me,null,a,d,f),e.l(d),qe(a,c))})}),Oe=Q(window),Pe=["tag_phone","js"].shift();Q(window);ea.push(ye);nc.push("_ym_debug");
ha.unshift(Be);ea.push(Ne);
var Qe=function(a){var b=window;K(v(T)(b),ha);return U(window,"m."+Pe,function(c,d,e){var f=Eb(c);"1570"!==e&&Ec(Hc("m.vc."+Pe));c=K(I,fa);e=P(f);var g={};g=C([b,e,"imnc",(g.key=e,g.module="tag_phone.js",g)],Pc);d&&ce(e,d);if(Oe.g("counters",{})[e]){K(function(l){l(b,f)},da);var h=[],k=function(l){l&&(x(l)?h.push(l):x(l.then)?l.then(k):!Ba(l)&&!y(l)&&"[object Object]"===Object.prototype.toString.call(l)&&l.u&&h.push(l.u))};d=function(l){l=l(b,f);k(l)};a&&a(b,f,d);ee(b,C([b,c,d,1,"a.i"],He));K(d,ea);
return C([T,h],K)}g()})}(void 0),Re=Oe.g("ytmm",{});if(!Re[Pe]){var Se={};Re[Pe]=(Se.init=Qe,Se);Oe.m("ytmm",Re)};}).call(this);
